### ISSUE TITLE
Add some awesome resources to your great list

### ISSUE THREAD

**Issue by ktaranov** [BrentOzar/sqlblogs#2]
Hi, Brent.

Checked your great reading list and compared with my, find some resources that could be interested for you:
 - https://www.sqlshack.com/
 - https://thelonedba.wordpress.com
 - http://sqlmag.com/
 - http://codingsight.com
 - https://blogs.msdn.microsoft.com/blogdoezequiel/

**Comment by BrentOzar** [comment]
Thanks! I'm skipping the MSDN one because they crosspost all their stuff over at Microsoft to other blogs, and skipping SQLmag because it's not really focused on SQL Server stuff anymore. Thanks!
